### ISSUE TITLE
Add support for the tweedie distribution in GLM models

### ISSUE THREAD

**Issue by ghost** [jpmml/jpmml-r#12]
Hi,

I need to convert a GLM with tweedie link function in R to pmml. I see the current version only support binomial or gaussian. Is there a way to do this or if you can guide me where to specify the parameter for link function in pmml. I have checked on pmml.org they support tweedie distribution.

Regards
Deepankar Arora

**Comment by vruusmann** [comment]
IIRC, the tweedie distribution uses `exp` as the inverse link function.

You can "transform" and ordinary (regression-type-) `RegressionModel` element to a tweedie one by specifying `RegressionModel@normalizationMethod="exp"`.

**Comment by vruusmann** [comment]
A rather trivial code change.

It's currently not implemented, because the R2PMML/JPMML-R integration testing suite does not include a suitable dataset. Should import the "Visit" dataset from the SkLearn2PMML/JPMML-SkLearn integration testing suite.
