### ISSUE TITLE
"The value for field  Species  is not defined" when i use xgboost comes to this problem,anyone can help?

### ISSUE THREAD

**Issue by topxxuki** [jpmml/jpmml-r#13]
R code

library(xgboost)
model2 <- xgboost(
  data = as.matrix(iris[, 1:4]),
  label = as.numeric(iris[, 5]) - 1,
  max_depth = 2, eta = 1, nthread = 2, nrounds = 2,
  objective = "multi:softprob", num_class = 3
)
as.matrix(iris[, 1:4])
#Save the tree information in an external file:
xgb.dump(model2, "model2.dumped.trees")
#Convert to PMML:
model.pmml<-pmml(model2,
     input_feature_names = colnames(as.matrix(iris[, 1:4])),
     missing_value_replacement=
     output_label_name = "Species",
     output_categories = c(1, 2, 3), xgb_dump_file = "model2.dumped.trees"
)
save_pmml(model.pmml, name="iris.xgb.pmml")

it seems "Species"has been defined in the pmml
![image](https://user-images.githubusercontent.com/18697846/62452453-cb9a9000-b7a2-11e9-85e2-8f14828b7f10.png)

**Comment by vruusmann** [comment]
The function `pmml.xgboost` belongs to the legacy `pmml` package, not here.
